title: iGive
email: support@igive.com
description: >-
  Have questions about using iGive.com or our browser extension when shopping online to raise money for your favorite local cause?
baseurl: ""
twitter_username: iGiveDoYou
facebook_username: iGive
gtm: GTM-TTQQRM
logo_tag: For Causes

collections_dir: content
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /:categories/:title/
  authors:
    output: true

keep_files: ["pagefind", "assets/pwa"]

include: ['.htaccess']
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile']

plugins:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-toc

toc:
  list_class: list-unstyled
  item_class: toc-entry toc-h4 mb-2

defaults:
  - scope:
      type: "pages"
    values:
      layout: page
  - scope:
      type: "posts"
    values:
      layout: post
      toc: true

pagination:
  enabled: true
  per_page: 1000
  permalink: '/page-:num'
  title: ':title'
  limit: 2
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

autopages:
  enabled: true
  categories:
    layouts:
      - list.html
    title: ':cat'
    permalink: '/:cat'
    slugify:
      mode: default
      case: true
  tags:
    layouts:
      - list.html
    title: ':tag'
    permalink: '/tag/:tag'
    slugify:
      mode: default
      case: true
  collections:
    layouts:
      - list.html
    title: ':collection'
    permalink: '/collection/:coll'
    slugify:
      mode: default
      case: true
sass:
  style: compressed